### PR TITLE
Use environment variable to skip jobset availability check

### PR DESCRIPTION
**Pull request by jiripetrlik**

### CODE REVIEW

**Review by Srihari1192 — APPROVED** [review]

**Review by Bobbins228 — CHANGES_REQUESTED** [review]
Can you amend the commit message to include 'CARRY'?

**Review by ChristianZaccaria — COMMENTED** [review]
/lgtm just needs the "CARRY" in the commit message.

The failing test seems unrelated to this change. I'm not too sure why it's failing though.

**Comment by jiripetrlik** [comment]
@Bobbins228 @ChristianZaccaria 
Should I use carry even if this PR was not propagated from community?

**Comment by ChristianZaccaria** [comment]
@jiripetrlik yes, CARRY are for our downstream commits we wish to retain permanently/long-term.

**Comment by jiripetrlik** [comment]
@ChristianZaccaria Thank you for explanation. I've added CARRY to the commit message.

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Review by sutaakar — APPROVED** [review]

**Review by Bobbins228 — APPROVED** [review]

**Pull request merged**
