### PR TITLE
PATCH: Exclude openshift namespaces from kueue VWebhook and MWebhook 

### PR DESCRIPTION
**Pull request by akram**
Add openshift namespaces exclusions to prevent kueue validating and mutating webhooks to interfere with system jobs

#### What type of PR is this?
Add openshift namespaces exclusions to prevent kueue validating and mutating webhooks to interfere with system jobs

/kind bug

#### What this PR does / why we need it:
Add openshift namespaces exclusions to prevent kueue validating and mutating webhooks to interfere with system jobs
Uses namespace selector to exclude jobs in relevant openshift-* namespaces to be blocked by kueue mutating and validating webhook in case of kueue being unavailable.

#### Which issue(s) this PR fixes:
Fixes https://issues.redhat.com/browse/RHOAIENG-14186

#### Special notes for your reviewer:
none

#### Does this PR introduce a user-facing change?
no

```release-note
Disable kueue-validating-webhook-configuration and kueue-mutating-webhook-configuration for jobs in some openshift-* namespaces to avoid kueue unavailability preventing system jobs to run.
```

### CODE REVIEW

**Review by ChristianZaccaria — COMMENTED** [review]
Thanks Akram! Works as expected:
- I set Kueue deployment to 0, then tested to submit a `Job`. The resource got created successfully and got no rejections from the kueue mutating webhook.

One small request, please update the commit message to include the prefix `PATCH: ` to better manage our downstream commits.

**Comment by akram** [comment]
Thanks for reviewing @ChristianZaccaria . I just updated the PR title . ✅

**Comment by ChristianZaccaria** [comment]
Hey Akram, I mean to rename the 'commit message' to include the prefix. This way maintaining our commit history as such:
https://github.com/opendatahub-io/kueue/commits/dev/

**Comment by akram** [comment]
ok, sorry, I just updated the commit message solely. And thanking out loud; I realised maybe instead of just set the `namespaceSelector` ; I can make a:

```
  - $patch: merge
    name: mjob.kb.io
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-system
        - kube-public
        - openshift
       ...
       
```

by doing a `kustomize` merge, that would be more resilient in case upstream decides to set `namespaceSelector` on `mjob` and `job` as well.


wdyt ?

**Review by ChristianZaccaria — APPROVED** [review]
/lgtm

**Pull request merged**
