### PR TITLE
CARRY: Use env variable 'NAMESPACE' for e2e tests

### PR DESCRIPTION
**Pull request by ChughShilpa**
Change namespace to opendatahub to run tests with rhoai overlay in [openshift CI](https://github.com/openshift/release/pull/48886#discussion_r1494483108)

### CODE REVIEW

**Comment by sutaakar** [comment]
@ChughShilpa Can you rather read the namespace from env variable? For product the namespace will differ.

**Comment by ChughShilpa** [comment]
> @ChughShilpa Can you rather read the namespace from env variable? For product the namespace will differ.

Updated the PR, Could you please review @sutaakar

**Review by sutaakar — APPROVED** [review]

**Comment by ChughShilpa** [comment]
Could you please review @astefanutti

**Review by astefanutti — COMMENTED** [review]
Could you please rebase the patch on the latest dev branch?

**Comment by ChughShilpa** [comment]
> Could you please rebase the patch on the latest dev branch?

Done

**Comment by astefanutti** [comment]
@ChughShilpa sorry we had to re-push dev branch so it's based on the correct Kueue version. Could you please rebase one last time?

**Comment by sutaakar** [comment]
@ChughShilpa Could you please rebase so there is only your commit on top of current dev branch?

**Comment by ChughShilpa** [comment]
Rebase it again @sutaakar @astefanutti

**Review by sutaakar — APPROVED** [review]
Looks good, thanks

**Review by astefanutti — APPROVED** [review]

**Pull request merged**
