### PR TITLE
CARRY: Integrate with OpenShift user workload monitoring

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by zdtsw** [comment]
> /cc @zdtsw could you please have a look and let us know if there is anything wrong with a component to create a PodMonitor resource to integrate with OpenShift user workload monitoring stack.


@astefanutti , I think these are two different parts of monitoring.
- UWM is the one component team can handle by yourselves. and it is not a blocker to get into downstream GA.
- SRE stack is the one required for Managed service, that will be sets of rules into downstream code base.

**Comment by astefanutti** [comment]
Tested with the latest changes:

image

**Comment by astefanutti** [comment]
@zdtsw 
> UWM is the one component team can handle by yourselves. and it is not a blocker to get into downstream GA.

That is what that PR addresses. Are you saying it's not a mandatory requirement for downstream GA?

We'd rather have this for 2.7 as the UXD team is going to start front-end development for Kueue.

**Comment by zdtsw** [comment]
> @zdtsw
> 
> > UWM is the one component team can handle by yourselves. and it is not a blocker to get into downstream GA.
> 
> That is what that PR addresses. Are you saying it's not a mandatory requirement for downstream GA?
> 
> We'd rather have this for 2.7 as the UXD team is going to start front-end development for Kueue.

I do not know how exactly the requirement on component in downstream regarding monitoring.
I agree that it is better to have monitoring than not have it, but I do not have much to say for , especially UWM part which i am not familiar with.

**Comment by astefanutti** [comment]
> I do not know how exactly the requirement on component in downstream regarding monitoring. I agree that it is better to have monitoring than not have it, but I do not have much to say for , especially UWM part which i am not familiar with.

Thanks. I just wanted to double check that there wouldn't be any objections on your side.

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
